name: BTReport
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2025.11.4
  - ld_impl_linux-64=2.44
  - libffi=3.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=1.1.1w
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.9.13
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - exceptiongroup==1.3.0
      - filelock==3.19.1
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - numpy==2.0.2
      - ollama==0.6.1
      - packaging==25.0
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - safetensors==0.6.2
      - sentencepiece==0.2.1
      - sniffio==1.3.1
      - tokenizers==0.22.1
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.5.0
prefix: /pscratch/sd/j/jehr/home_moved/conda_envs/BTReport
