name: BTReport
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.11.4=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.3=he6710b0_2
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.13=haa1d7c7_2
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - accelerate==0.30.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - bert-score==0.3.13
      - blis==0.7.11
      - catalogue==2.0.10
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - cloudpathlib==0.23.0
      - comm==0.2.3
      - confection==0.1.5
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.13
      - cython==3.1.7
      - datasets==2.19.0
      - debugpy==1.8.17
      - decorator==5.2.1
      - dill==0.3.8
      - dotmap==1.3.30
      - emoji==2.15.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - filelock==3.19.1
      - fonttools==4.60.1
      - formulaic==1.2.1
      - frozenlist==1.8.0
      - fsspec==2024.3.1
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - interface-meta==1.3.0
      - ipykernel==6.31.0
      - ipython==8.18.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonpickle==4.1.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - lifelines==0.30.0
      - loguru==0.7.3
      - marisa-trie==1.3.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - medspacy==1.3.1
      - medspacy-quickumls==3.2
      - medspacy-unqlite==0.9.8
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - murmurhash==1.0.15
      - narwhals==2.12.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - neurite==0.2
      - nibabel==5.3.2
      - nltk==3.9.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - ollama==0.6.1
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==10.3.0
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - preshed==3.0.12
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.1
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==21.0.0
      - pyarrow-hotfix==0.7
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pyfastner==1.0.10
      - pygments==2.19.2
      - pyparsing==3.2.5
      - pyrush==1.0.12
      - pysbd==0.3.4
      - pysimstring==1.3.0
      - pystrum==0.4
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - quicksectx==0.4.1
      - radeval==0.0.1rc6
      - radgraph==0.1.18
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rouge-score==0.1.2
      - rpds-py==0.27.1
      - safetensors==0.6.2
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentence-transformers==3.0.1
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.5.0
      - sniffio==1.3.1
      - spacy==3.7.5
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.2
      - stack-data==0.6.3
      - stanza==1.11.0
      - sympy==1.14.0
      - thinc==8.2.5
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.2.2
      - torchvision==0.17.2
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.1
      - triton==2.2.0
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - unidecode==1.4.0
      - urllib3==2.5.0
      - voxelmorph==0.2
      - wasabi==1.1.3
      - wcwidth==0.2.14
      - weasel==0.4.3
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
